// <auto-generated />
using System;
using AiNutritionTracking.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiNutritionTracking.API.Migrations
{
    [DbContext(typeof(AinutritiontrackingContext))]
    partial class AinutritiontrackingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiNutritionTracking.API.Models.AichatMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("SenderType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer");

                    b.HasKey("MessageId")
                        .HasName("AIChatMessages_pkey");

                    b.HasIndex("SessionId");

                    b.ToTable("AIChatMessages", (string)null);
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.AichatSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("SessionId")
                        .HasName("AIChatSessions_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("AIChatSessions", (string)null);
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.AiextractedField", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FieldId"));

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FieldType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParsedValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RawValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ResponseId")
                        .HasColumnType("integer");

                    b.HasKey("FieldId")
                        .HasName("AIExtractedFields_pkey");

                    b.HasIndex("ResponseId");

                    b.ToTable("AIExtractedFields", (string)null);
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Airecommendation", b =>
                {
                    b.Property<int>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecommendationId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RecommendationType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("RecommendationId")
                        .HasName("AIRecommendations_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("AIRecommendations", (string)null);
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Airequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<string>("Aimodel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("AIModel");

                    b.Property<string>("Aiprovider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("AIProvider");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("InputImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Prompt")
                        .HasColumnType("text");

                    b.Property<string>("RequestType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("RequestId")
                        .HasName("AIRequests_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("AIRequests", (string)null);
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Airesponse", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResponseId"));

                    b.Property<double?>("CaloriesEstimate")
                        .HasColumnType("double precision");

                    b.Property<double?>("CarbEstimate")
                        .HasColumnType("double precision");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<double?>("FatEstimate")
                        .HasColumnType("double precision");

                    b.Property<string>("GeneratedMealPlan")
                        .HasColumnType("text");

                    b.Property<double?>("ProteinEstimate")
                        .HasColumnType("double precision");

                    b.Property<string>("RawResponse")
                        .HasColumnType("text");

                    b.Property<int?>("RequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("ResponseId")
                        .HasName("AIResponses_pkey");

                    b.HasIndex("RequestId");

                    b.ToTable("AIResponses", (string)null);
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Allergy", b =>
                {
                    b.Property<int>("AllergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AllergyId"));

                    b.Property<string>("AllergyName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AllergyId")
                        .HasName("Allergies_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("PostId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CommentId")
                        .HasName("Comments_pkey");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExerciseId"));

                    b.Property<double?>("CaloriesBurnedPerHour")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ExerciseName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("ExerciseId")
                        .HasName("Exercises_pkey");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.ExerciseLog", b =>
                {
                    b.Property<int>("ExerciseLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExerciseLogId"));

                    b.Property<double?>("CaloriesBurned")
                        .HasColumnType("double precision");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ExerciseLogId")
                        .HasName("ExerciseLogs_pkey");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId");

                    b.ToTable("ExerciseLogs");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.FavoriteFood", b =>
                {
                    b.Property<int>("FavoriteFoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FavoriteFoodId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("FoodId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FavoriteFoodId")
                        .HasName("FavoriteFoods_pkey");

                    b.HasIndex("FoodId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteFoods");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FoodId"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double?>("Carbs")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double?>("Fat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Fiber")
                        .HasColumnType("double precision");

                    b.Property<string>("FoodType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("Protein")
                        .HasColumnType("double precision");

                    b.Property<string>("ServingSize")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Sodium")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.Property<double?>("Sugar")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("FoodId")
                        .HasName("Foods_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Meal", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("MealDate")
                        .HasColumnType("date");

                    b.Property<string>("MealType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double?>("TotalCalories")
                        .HasColumnType("double precision");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("MealId")
                        .HasName("Meals_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.MealItem", b =>
                {
                    b.Property<int>("MealItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealItemId"));

                    b.Property<double?>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double?>("Carbs")
                        .HasColumnType("double precision");

                    b.Property<double?>("Fat")
                        .HasColumnType("double precision");

                    b.Property<int?>("FoodId")
                        .HasColumnType("integer");

                    b.Property<int?>("MealId")
                        .HasColumnType("integer");

                    b.Property<double?>("Protein")
                        .HasColumnType("double precision");

                    b.Property<double?>("Quantity")
                        .HasColumnType("double precision");

                    b.HasKey("MealItemId")
                        .HasName("MealItems_pkey");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealId");

                    b.ToTable("MealItems");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'Sent'::character varying");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("NotificationId")
                        .HasName("Notifications_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("LikesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PostId")
                        .HasName("Posts_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeId"));

                    b.Property<int?>("CookingTime")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("RecipeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'Pending'::character varying");

                    b.Property<double?>("TotalCalories")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId")
                        .HasName("Recipes_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.RecipeItem", b =>
                {
                    b.Property<int>("RecipeItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeItemId"));

                    b.Property<int?>("FoodId")
                        .HasColumnType("integer");

                    b.Property<double?>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RecipeItemId")
                        .HasName("RecipeItems_pkey");

                    b.HasIndex("FoodId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeItems");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("ReporterUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'Pending'::character varying");

                    b.Property<int?>("TargetId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ReportId")
                        .HasName("Reports_pkey");

                    b.HasIndex("ReporterUserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId")
                        .HasName("Roles_pkey");

                    b.HasIndex(new[] { "RoleName" }, "Roles_RoleName_key")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("BodyFat")
                        .HasColumnType("double precision");

                    b.Property<int?>("CaloriesTarget")
                        .HasColumnType("integer");

                    b.Property<double?>("CarbTarget")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmailVerificationTokenHash")
                        .HasColumnType("text");

                    b.Property<bool?>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<double?>("FatTarget")
                        .HasColumnType("double precision");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Goal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double?>("ProteinTarget")
                        .HasColumnType("double precision");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.Property<double?>("TargetWeight")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("UserId")
                        .HasName("Users_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "Users_Email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "Users_Username_key")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.UserHealthCondition", b =>
                {
                    b.Property<int>("ConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConditionId"));

                    b.Property<string>("ConditionName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ConditionId")
                        .HasName("UserHealthConditions_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("UserHealthConditions");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.WaterLog", b =>
                {
                    b.Property<int>("WaterLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WaterLogId"));

                    b.Property<double?>("AmountMl")
                        .HasColumnType("double precision")
                        .HasColumnName("AmountML");

                    b.Property<DateTime?>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("WaterLogId")
                        .HasName("WaterLogs_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("WaterLogs");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.WeightLog", b =>
                {
                    b.Property<int>("WeightLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WeightLogId"));

                    b.Property<double?>("BodyFat")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("WeightLogId")
                        .HasName("WeightLogs_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("WeightLogs");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.AichatMessage", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.AichatSession", "Session")
                        .WithMany("AichatMessages")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("AIChatMessages_SessionId_fkey");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.AichatSession", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.User", "User")
                        .WithMany("AichatSessions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("AIChatSessions_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.AiextractedField", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.Airesponse", "Response")
                        .WithMany("AiextractedFields")
                        .HasForeignKey("ResponseId")
                        .HasConstraintName("AIExtractedFields_ResponseId_fkey");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Airecommendation", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.User", "User")
                        .WithMany("Airecommendations")
                        .HasForeignKey("UserId")
                        .HasConstraintName("AIRecommendations_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Airequest", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.User", "User")
                        .WithMany("Airequests")
                        .HasForeignKey("UserId")
                        .HasConstraintName("AIRequests_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Airesponse", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.Airequest", "Request")
                        .WithMany("Airesponses")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("AIResponses_RequestId_fkey");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Allergy", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.User", "User")
                        .WithMany("Allergies")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Allergies_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Comment", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .HasConstraintName("Comments_PostId_fkey");

                    b.HasOne("AiNutritionTracking.API.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Comments_UserId_fkey");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.ExerciseLog", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.Exercise", "Exercise")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("ExerciseId")
                        .HasConstraintName("ExerciseLogs_ExerciseId_fkey");

                    b.HasOne("AiNutritionTracking.API.Models.User", "User")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("ExerciseLogs_UserId_fkey");

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.FavoriteFood", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.Food", "Food")
                        .WithMany("FavoriteFoods")
                        .HasForeignKey("FoodId")
                        .HasConstraintName("FavoriteFoods_FoodId_fkey");

                    b.HasOne("AiNutritionTracking.API.Models.User", "User")
                        .WithMany("FavoriteFoods")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FavoriteFoods_UserId_fkey");

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Food", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.User", "CreatedByNavigation")
                        .WithMany("FoodCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("Foods_CreatedBy_fkey");

                    b.HasOne("AiNutritionTracking.API.Models.User", "UpdatedByNavigation")
                        .WithMany("FoodUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("Foods_UpdatedBy_fkey");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Meal", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.User", "User")
                        .WithMany("Meals")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Meals_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.MealItem", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.Food", "Food")
                        .WithMany("MealItems")
                        .HasForeignKey("FoodId")
                        .HasConstraintName("MealItems_FoodId_fkey");

                    b.HasOne("AiNutritionTracking.API.Models.Meal", "Meal")
                        .WithMany("MealItems")
                        .HasForeignKey("MealId")
                        .HasConstraintName("MealItems_MealId_fkey");

                    b.Navigation("Food");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Notification", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Notifications_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Post", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Posts_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Recipe", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Recipes_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.RecipeItem", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.Food", "Food")
                        .WithMany("RecipeItems")
                        .HasForeignKey("FoodId")
                        .HasConstraintName("RecipeItems_FoodId_fkey");

                    b.HasOne("AiNutritionTracking.API.Models.Recipe", "Recipe")
                        .WithMany("RecipeItems")
                        .HasForeignKey("RecipeId")
                        .HasConstraintName("RecipeItems_RecipeId_fkey");

                    b.Navigation("Food");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Report", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.User", "ReporterUser")
                        .WithMany("Reports")
                        .HasForeignKey("ReporterUserId")
                        .HasConstraintName("Reports_ReporterUserId_fkey");

                    b.Navigation("ReporterUser");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.User", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("Users_RoleId_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.UserHealthCondition", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.User", "User")
                        .WithMany("UserHealthConditions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("UserHealthConditions_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.WaterLog", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.User", "User")
                        .WithMany("WaterLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("WaterLogs_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.WeightLog", b =>
                {
                    b.HasOne("AiNutritionTracking.API.Models.User", "User")
                        .WithMany("WeightLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("WeightLogs_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.AichatSession", b =>
                {
                    b.Navigation("AichatMessages");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Airequest", b =>
                {
                    b.Navigation("Airesponses");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Airesponse", b =>
                {
                    b.Navigation("AiextractedFields");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Exercise", b =>
                {
                    b.Navigation("ExerciseLogs");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Food", b =>
                {
                    b.Navigation("FavoriteFoods");

                    b.Navigation("MealItems");

                    b.Navigation("RecipeItems");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Meal", b =>
                {
                    b.Navigation("MealItems");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Recipe", b =>
                {
                    b.Navigation("RecipeItems");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AiNutritionTracking.API.Models.User", b =>
                {
                    b.Navigation("AichatSessions");

                    b.Navigation("Airecommendations");

                    b.Navigation("Airequests");

                    b.Navigation("Allergies");

                    b.Navigation("Comments");

                    b.Navigation("ExerciseLogs");

                    b.Navigation("FavoriteFoods");

                    b.Navigation("FoodCreatedByNavigations");

                    b.Navigation("FoodUpdatedByNavigations");

                    b.Navigation("Meals");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");

                    b.Navigation("Recipes");

                    b.Navigation("Reports");

                    b.Navigation("UserHealthConditions");

                    b.Navigation("WaterLogs");

                    b.Navigation("WeightLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
